CREATE TABLE accounts(id INTEGER PRIMARY KEY, profile TEXT NOT NULL DEFAULT '{}', registered_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, generation TEXT NOT NULL);
CREATE TABLE account_meta(user_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,key TEXT NOT NULL,value TEXT NOT NULL,PRIMARY KEY(user_id,key));
INSERT OR IGNORE INTO accounts SELECT owner_id, json_extract(payload,'$.user'), updated_at,updated_at,lower(hex(randomblob(16))) FROM connections;
INSERT OR IGNORE INTO accounts SELECT CAST(value AS INTEGER), COALESCE((SELECT value FROM meta WHERE key='owner_profile'),'{}'),strftime('%s','now'),strftime('%s','now'),lower(hex(randomblob(16))) FROM meta WHERE key='owner_id' AND CAST(value AS INTEGER)>0;
INSERT OR IGNORE INTO accounts SELECT chat_id,'{}',first_seen,first_seen,lower(hex(randomblob(16))) FROM messages WHERE connection_id='dm';
UPDATE accounts SET profile=(SELECT value FROM meta WHERE key='owner_profile') WHERE id=(SELECT CAST(value AS INTEGER) FROM meta WHERE key='owner_id') AND EXISTS(SELECT 1 FROM meta WHERE key='owner_profile');
INSERT OR IGNORE INTO account_meta SELECT CAST(o.value AS INTEGER),m.key,m.value FROM meta m JOIN meta o ON o.key='owner_id' WHERE CAST(o.value AS INTEGER)>0 AND (m.key IN ('lang','plan','input_mode','welcome_sent','ui_message_id','api_hash','archive_route','last_business_update') OR m.key LIKE 'setting:%' OR m.key LIKE 'ui_hash:%');
DELETE FROM account_meta WHERE key='input_mode';
PRAGMA defer_foreign_keys=ON;
UPDATE messages SET connection_id='dm:'||chat_id WHERE connection_id='dm';
UPDATE versions SET connection_id='dm:'||chat_id WHERE connection_id='dm';
UPDATE saved SET connection_id='dm:'||chat_id WHERE connection_id='dm';
UPDATE deletions SET connection_id='dm:'||chat_id WHERE connection_id='dm';
UPDATE chats SET connection_id='dm:'||id WHERE connection_id='dm';
UPDATE chat_settings SET connection_id='dm:'||chat_id WHERE connection_id='dm';
UPDATE users SET connection_id='dm:'||COALESCE((SELECT value FROM meta WHERE key='owner_id'),id) WHERE connection_id='dm';
UPDATE user_history SET connection_id='dm:'||COALESCE((SELECT value FROM meta WHERE key='owner_id'),user_id) WHERE connection_id='dm';
UPDATE watches SET connection_id='dm:'||COALESCE((SELECT value FROM meta WHERE key='owner_id'),user_id) WHERE connection_id='dm';
DELETE FROM meta WHERE key IN ('owner_id','owner_profile','lang','plan','input_mode','welcome_sent','ui_message_id','api_hash','archive_route','last_business_update') OR key LIKE 'setting:%' OR key LIKE 'ui_hash:%';
ALTER TABLE outbox ADD COLUMN tenant_id INTEGER REFERENCES accounts(id) ON DELETE CASCADE;
ALTER TABLE outbox ADD COLUMN response_message_id INTEGER;
UPDATE outbox SET tenant_id=(SELECT id FROM accounts WHERE id=COALESCE((SELECT owner_id FROM connections WHERE id=json_extract(outbox.payload,'$.business_connection_id')),CAST(json_extract(payload,'$.chat_id') AS INTEGER))) WHERE state!='sent';
UPDATE outbox SET tenant_id=(SELECT id FROM accounts LIMIT 1) WHERE tenant_id IS NULL AND (SELECT count(*) FROM accounts)=1;
CREATE TABLE jobs(id INTEGER PRIMARY KEY,tenant_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,update_id INTEGER NOT NULL,kind TEXT NOT NULL,payload TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'pending',created_at INTEGER NOT NULL,UNIQUE(tenant_id,update_id,kind));
CREATE TABLE usage_limits(tenant_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,kind TEXT NOT NULL,window INTEGER NOT NULL,count INTEGER NOT NULL,PRIMARY KEY(tenant_id,kind));
CREATE TABLE revoked_connections(id TEXT PRIMARY KEY,revoked_at INTEGER NOT NULL);
CREATE TABLE processed_actions(tenant_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,update_id INTEGER NOT NULL,applied_at INTEGER NOT NULL,PRIMARY KEY(tenant_id,update_id));
INSERT INTO processed_actions SELECT (SELECT id FROM accounts LIMIT 1),update_id,applied_at FROM ui_actions WHERE (SELECT count(*) FROM accounts)=1;
DROP TABLE ui_actions;
CREATE INDEX idx_connections_owner ON connections(owner_id);
CREATE INDEX idx_jobs_pending ON jobs(state,created_at);
CREATE TRIGGER immutable_connection_owner BEFORE UPDATE OF owner_id ON connections WHEN OLD.owner_id!=NEW.owner_id BEGIN SELECT RAISE(ABORT,'Connection ownership cannot change'); END;
